<?php
declare(strict_types=1);
include_once 'classes/autoloader.php';
$database=new \projekt\classes\Dbhandler();
$database->mySql();
$database->dbConnect();
$database->setTable('products');
$title = 'Add Product';
include_once("templates/top.php");
$form=new \projekt\classes\Form;
$form->createFormTop("POST", "Product List");
$form->addSubmitButton("action/add-product.php", "Save");
$form->addFunctionButton("window.location.href = 'index.php';");
$form->createFormMiddle();
$pattern=$database->createSKUPattern($database->getSKUArray());
$form->addFormInput("SKU","SKU","text",'oninput="this.value.toUpperCase()"','pattern='.$pattern.'');
$form->addFieldChecker("skucheck");
$form->addFormInput("Name","Name","text");
$form->addFieldChecker("namecheck");
$form->addFormInput("Price","Price","text");
$form->addFieldChecker("pricecheck");
$form->addFormSelect("productType");
$form->addOption("", "disabled", "selected");
$form->addOption("DVD");
$form->addOption("Book");
$form->addOption("Furniture");
$form->closeFormSelect();
$form->addFieldChecker("productcheck");
$form->addFormWindow();
include_once("templates/bottom.php");
?>
